server.port: 8082
management:
  endpoints:
    web:
      exposure:
        include: '*'
security:
  oauth2:
    resource:
      id: service
      user-info-uri: http://localhost:8080/user
logging:
  level:
    org.springframework.security: DEBUG